konstructio/console

utils/cards.ts

- Updating Vault, ArgoCD, and Atlantis doc links
Fixes: https://github.com/kubefirst/kubefirst/issues/1123

feat: Console link updates

---

components/clusterDetails/index.tsx
components/table/index.tsx
containers/clusterForms/shared/authForm/index.tsx
containers/clusterManagement/columnDefinition.tsx
containers/provision/index.tsx
hooks/useInstallation.ts
redux/thunks/cluster.thunk.ts
types/redux/index.ts

- UX feedback
- Auth form fields

feat: auth form fields

---

components/autocomplete/index.tsx
components/gitOpsCatalogCard/gitOpsCatalogCard.styled.ts
components/gitOpsCatalogCard/index.tsx
components/gitopsAppModal/index.tsx
components/installationStepContainer/installationStepContainer.styled.ts
constants/colors.ts
constants/index.ts
containers/clusterForms/aws/setupForm/index.tsx
containers/clusterForms/civo/setupForm/index.tsx
containers/clusterForms/digitalocean/setupForm/index.tsx
containers/clusterForms/shared/advancedOptions/index.tsx
containers/clusterForms/vultr/setupForm/index.tsx
containers/gitOpsCatalog/index.tsx
containers/header/index.tsx
containers/provision/index.tsx
containers/services/index.tsx
hooks/useInstallation.ts
package.json
pages/_app.tsx
redux/slices/api.slice.ts
redux/slices/cluster.slice.ts
redux/slices/installation.slice.ts
redux/store.ts
redux/thunks/api.thunk.ts
utils/cards.ts
utils/localStorage/index.ts
yarn.lock

- adds redux persist in localstorage
- block sensitive data from persist
- auth validation when clicking next from the auth form
- gitops catalog loading state

feat: persist state

---

assets/add.svg
assets/remove.svg
components/numberInput/index.tsx
components/numberInput/numberInput.stories.tsx
components/numberInput/numberInput.styled.ts

chore: add number input needed for cluster management form

---

components/gitOpsCatalogCard/gitOpsCatalogCard.styled.ts
components/gitOpsCatalogCard/index.tsx
components/tag/index.tsx
components/tag/tag.styled.ts
containers/gitOpsCatalog/index.tsx
redux/slices/cluster.slice.ts
types/gitOpsCatalog/index.ts

reference:
https://www.notion.so/kubeshop/Enhancements-GitOps-catalog-0158ee8ac6f8465fa697506c6b4ba019

Gitops catalog tag label update

---

components/clusterTable/clusterTable.tsx
components/flow/index.tsx
components/graphNode/index.tsx
constants/index.ts
containers/clusterManagement/index.tsx
redux/slices/reactFlow.slice.ts
types/provision/index.ts
utils/reactFlow/index.ts

https://github.com/kubefirst/console/assets/76881293/962b16ca-f1c6-4598-b929-79a5296121c6

React flow node interaction

---

assets/closeRounded.svg
assets/lightningBolt.svg
components/headsUpNotification/headsUpNotification.stories.tsx
components/headsUpNotification/headsUpNotification.styled.ts
components/headsUpNotification/index.tsx

chore: add heads up notification comp

---

components/tag/index.tsx
components/tag/tag.stories.tsx
components/tag/tag.styled.ts

refactor: add option for removable tag for selectable lists

---

cypress/e2e/1-create-cluster/add-workload-cluster.cy.ts
cypress/e2e/1-create-cluster/management-cluster-provision.cy.ts
cypress/e2e/console.cy.ts
cypress/support/commands.ts
tsconfig.json
utils/types/index.ts

I want my types.
no more squigglies

Cypress types

---

hooks/useQueue/queue.context.ts
package.json
yarn.lock

Cleans up build warnings for barrel optimize

update next@13.5.6. add defaults to context

---

components/autocomplete/index.tsx
components/controlledFields/AutoComplete.tsx
components/controlledFields/Password.tsx
containers/clusterForms/shared/authForm/index.tsx
redux/slices/git.slice.ts
redux/thunks/__tests__/git.thunk.test.ts

https://github.com/kubefirst/console/assets/76881293/98743a25-10d5-4f63-86a7-1c7a4a3f538c

Auth form validation bug

---

components/banner/banner.stories.tsx
components/banner/banner.styled.ts
components/banner/index.tsx
components/controlledFields/radio/index.tsx
components/controlledFields/radio/radio.stories.tsx
components/tag/index.tsx
components/tag/tag.styled.ts
constants/colors.ts
containers/clusterForms/clusterCreation/index.tsx
containers/clusterManagement/clusterManagement.styled.ts
containers/clusterManagement/createClusterFlow/index.tsx
containers/clusterManagement/index.tsx
containers/layout/index.tsx
containers/layout/layout.styled.ts
hooks/usePaywall.ts
redux/selectors/subscription.selector.ts
redux/slices/settings.slice.ts
types/subscription/index.ts

feat: payment validation

---

components/banner/banner.styled.ts
components/controlledFields/TextField.tsx
components/controlledFields/textArea/index.tsx
components/textField/index.tsx
constants/colors.ts
containers/cancelSubscription/cancelSubscriptionConfirmation/index.tsx
containers/cancelSubscription/cancelSubscriptionForm/index.tsx
containers/cancelSubscription/index.tsx
containers/contactUsModal/contactUsForm/contactUsForm.styled.ts
containers/contactUsModal/contactUsForm/index.tsx
containers/contactUsModal/index.tsx
containers/license/index.tsx
containers/license/license.styled.ts
containers/subscription/index.tsx
hooks/usePaywall.ts
redux/selectors/subscription.selector.ts
redux/thunks/subscription.thunk.ts
types/subscription/index.ts

https://github.com/kubefirst/console/assets/14883029/4704d66e-ee0c-422d-b14a-e415e9085ff4
src="https://github.com/kubefirst/console/assets/14883029/f9f42f2c-cf80-43a0-8f4e-83e78afb23e3">
https://github.com/kubefirst/console/assets/14883029/566723c9-bca7-482a-b137-c791e329c9c3

feat: cancel subscription and upgrate to enterprise user requests

---

components/gitOpsCatalogCard/index.tsx

place tooltip above description as to not block install button.

---

containers/header/index.tsx
containers/navigation/index.tsx
containers/terminalLogs/terminalLogs.tsx
pages/api/stream/[logFile].ts
redux/thunks/api.thunk.ts
tests/mocks/mockClusterResponse.ts
types/provision/index.ts
utils/isJson.ts
utils/mapClustersFromRaw.ts

feat: logs

---

components/clusterDetails/clusterDetails.styled.ts
components/clusterDetails/index.tsx
containers/clusterManagement/createClusterFlow/index.tsx

update cluster details to match updated designs

---

components/gitopsAppModal/index.tsx
containers/gitOpsCatalog/index.tsx
redux/thunks/cluster.thunk.ts
types/gitOpsCatalog/index.ts

feat: add config keys to gitops catalog modal

---

components/Application/Application.tsx
components/UninstallApplication/UninstallApplication.tsx
containers/Applications/Applications.tsx
pages/api/proxy.ts
redux/slices/applications.slice.ts
redux/thunks/applications.thunk.ts
types/applications/index.ts

- Uninstall state
- Delete confirmation
https://github.com/kubefirst/console/assets/14883029/9b946567-7dcb-42af-ae19-6e66410def01

feat: gitops catalog delete confirmation modal

---

components/CloudProviderCard/CloudProviderCard.styled.ts

fix: remove vertical scrollbars on clouds cards

---

components/Autocomplete/Autocomplete.tsx

Fixes: https://github.com/kubefirst/kubefirst/issues/2164

fix: autocomplete indicator

---

containers/ClusterManagement/ClusterManagement.tsx

Fixes: https://github.com/kubefirst/kubefirst/issues/2208

feat: disable joyride tour

---

.argo/publish.yaml
.argo/release.yaml
.argo/trigger.yaml

adopting new microservice pattern in ci

chore: adopting new microservice pattern in ci

---

.argo/publish.yaml

adjusting details of where the macro chart version comes from during microservice publish

adjusting chart version details

---

.devcontainer/devcontainer.json
README.md

Provide development environment as code
Fixes #
- Ensure that the [dev container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension is installed to VSCode
- Open up repo in VSCode
- When prompted, reopen in container

chore: add devcontainer for local development

---

.editorconfig

Fixes https://github.com/kubefirst/kubefirst/issues/2239

chore: add support for editorconfig

---

app/settings/subscription/[slug]/page.tsx
app/settings/subscription/page.tsx
containers/ClusterManagement/ClusterManagement.tsx
hooks/usePaywall.ts
redux/slices/applications.slice.ts

- There was a runtime issue, when the applications endpoint is returning null for new environments
- Handling error for subscription plans

fix: gitops catalog filter and handle subscription error

---

hooks/usePaywall.ts

- Fixing cluster limit for free tier

fix: cluster limit for free tier

---

app/auth/signin/page.tsx
charts/console/values.yaml
constants/index.ts
containers/ClusterForms/shared/AdvancedOptions/AdvancedOptions.tsx
containers/GitOpsCatalog/GitOpsCatalog.tsx
containers/Header/Header.tsx
containers/License/License.tsx
containers/Navigation/Navigation.tsx

This PR updates konstruct.io links

chore: update konstruct links

---

containers/ClusterForms/shared/__tests__/ClusterRunning.test.tsx
tests/setup.tsx

chore: improve unit test

---

components/TextField/TextField.tsx
hooks/useInstallation.ts

-Select wasn't showing the options

fix: select

---

components/CloudProviderCard/CloudProviderCard.tsx

- Move clouds of beta, remove beta tag

feat: move clouds out of beta

---

constants/cluster.tsx
containers/ClusterForms/shared/SetupForm.tsx
redux/thunks/api.thunk.ts
types/redux/index.ts

- Adding AMI Types for AWS provision

feat: ami type for mgmt cluster

---

next.config.js

fix: headers
